# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XnM6RtK3blwRYJ_HhlEyec0QZqM9mcC
"""

!pip install -U langchain langchain-community langchain-text-splitters chromadb pypdf sentence-transformers transformers

from google.colab import files
uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import PromptTemplate
from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline
from datetime import datetime

file_name = list(uploaded.keys())[0]

loader = PyPDFLoader(file_name)
documents = loader.load()

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = splitter.split_documents(documents)

print("Total chunks created:", len(chunks))

from langchain_community.document_loaders import PyPDFLoader

pdf_files = ["paper1_large.pdf", "notes1_large.pdf"]
documents = []

for file in pdf_files:
    loader = PyPDFLoader(file)
    docs = loader.load()
    documents.extend(docs)

print("Total pages loaded:", len(documents))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = splitter.split_documents(documents)

print(" Total chunks created:", len(chunks))

for chunk in chunks:
    meta = chunk.metadata

    chunk.metadata = {
        "filename": meta.get("source", ""),
        "page_number": meta.get("page", -1),
        "upload_date": datetime.now().strftime("%Y-%m-%d")
    }

print(" Metadata added")

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embedding
)

print(" Stored in ChromaDB")

retriever = vectorstore.as_retriever(search_kwargs={"k": 2})

print(" Retriever ready")

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
Answer ONLY using the context below.
Do NOT generate questions.
Do NOT repeat the prompt.

Context:
{context}

Question:
{question}

Answer:
"""
)

pipe = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_length=512,
    temperature=0.5
)

llm = HuggingFacePipeline(pipeline=pipe)

def rag_chain(question):
    docs = retriever.invoke(question)

    if not docs:
        return [], "No relevant info found."

    context = "\n\n".join([doc.page_content for doc in docs])

    final_prompt = prompt.format(
        context=context,
        question=question
    )

    response = llm.invoke(final_prompt)

    return docs, response

questions = [
    "What is the main topic of the document?",
    "Explain important concepts.",
    "What are the conclusions?"
]

for q in questions:
    print("\n=============================")
    print("Question:", q)

    docs, answer = rag_chain(q)

    print("\nAnswer:")
    print(answer)